/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IProposalIncentivesExecutor } from "../IProposalIncentivesExecutor";

export class IProposalIncentivesExecutor__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProposalIncentivesExecutor {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IProposalIncentivesExecutor;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address[6]",
        name: "aTokenImplementations",
        type: "address[6]",
      },
      {
        internalType: "address[6]",
        name: "variableDebtImplementation",
        type: "address[6]",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
