/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IControllerAaveEcosystemReserve } from "../IControllerAaveEcosystemReserve";

export class IControllerAaveEcosystemReserve__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IControllerAaveEcosystemReserve {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IControllerAaveEcosystemReserve;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
